import Foundation

/// The live catalogue. These are real, creator-supplied works — their media
/// files live in `Resources/Samples` and are wired by `coverAssetName` /
/// `mediaFileName` slugs (see ContentResolver). No demo/placeholder content.
enum SampleData {
    static func catalog() -> [MediaItem] {
        [
            MediaItem(
                id: UUID(uuidString: "11111111-1111-4111-8111-111111111111")!,
                title: "The Odyssey Protocol",
                creator: "Mike Valasek",
                type: .novel,
                genre: "Literary Sci-Fi Thriller",
                synopsis: "Marine scientist Helena Karras knows the Aegean is lying to her. When the sea goes impossibly, unnaturally still over the research vessel Aegis, she's pulled into a mystery that reaches from Homer's Odyssey to the edge of the unknown — and asks what it means to keep sailing toward the thing that could destroy you. A 70,000-word novel.",
                aiTools: ["Claude Opus 4.7", "GPT-4"],
                commercialScore: 94,
                price: 7.99,
                releaseYear: 2026,
                length: 286,
                maturity: "13+",
                purchases: 0,
                trending: 72,
                coverAssetName: "the-odyssey-protocol",
                mediaFileName: "the-odyssey-protocol"
            ),
            MediaItem(
                id: UUID(uuidString: "10ad1040-1040-4040-8040-104010401040")!,
                title: "The Love Algorithm",
                creator: "Mike Valasek",
                type: .novel,
                genre: "Relationships",
                synopsis: "A data-age field guide to love, power, and attraction. The Love Algorithm decodes the hidden dynamics of the modern relationship market — why we fall for the wrong people, how to read the signs before it breaks you, and how to understand your real value in the age of algorithms. Take the test. Read the signs. Know the truth.",
                aiTools: ["GPT-4"],
                commercialScore: 91,
                price: 6.99,
                releaseYear: 2026,
                length: 248,
                maturity: "17+",
                purchases: 0,
                trending: 68,
                coverAssetName: "the-love-algorithm",
                mediaFileName: "the-love-algorithm"
            ),
            MediaItem(
                id: UUID(uuidString: "22222222-2222-4222-8222-222222222222")!,
                title: "It's a Swifty World After All",
                creator: "Mike Valasek",
                type: .music,
                genre: "Pop",
                synopsis: "A glittering pop anthem with stadium-sized hooks and a wink in every line. Written by Mike Valasek and brought to life with Suno — bright, buoyant, and built around a chorus you'll be humming all day.",
                aiTools: ["Suno"],
                commercialScore: 90,
                price: 1.29,
                releaseYear: 2026,
                length: 1,
                maturity: "Everyone",
                purchases: 0,
                trending: 66,
                coverAssetName: "its-a-swifty-world-after-all",
                mediaFileName: "its-a-swifty-world-after-all",
                coverHasTitle: true
            ),
            MediaItem(
                id: UUID(uuidString: "33333333-3333-4333-8333-333333333333")!,
                title: "Curves Like Keisha",
                creator: "Mike Valasek",
                type: .music,
                genre: "Hip-Hop / R&B",
                synopsis: "A smooth hip-hop / R&B cut with a confident groove and a melody that struts. Human songwriting by Mike Valasek, realized with Suno — late-night, low-lit, and effortlessly cool.",
                aiTools: ["Suno"],
                commercialScore: 89,
                price: 1.29,
                releaseYear: 2026,
                length: 1,
                maturity: "13+",
                purchases: 0,
                trending: 61,
                coverAssetName: "curves-like-keisha",
                mediaFileName: "curves-like-keisha",
                coverHasTitle: true
            ),
            MediaItem(
                id: UUID(uuidString: "44444444-4444-4444-8444-444444444444")!,
                title: "Push Up Bra",
                creator: "Mike Valasek",
                type: .music,
                genre: "Pop",
                synopsis: "A cheeky, high-energy pop track that doesn't take itself too seriously. Written by Mike Valasek and produced with Suno — playful, punchy, and unapologetically catchy.",
                aiTools: ["Suno"],
                commercialScore: 88,
                price: 1.29,
                releaseYear: 2026,
                length: 1,
                maturity: "13+",
                purchases: 0,
                trending: 58,
                coverAssetName: "push-up-bra",
                mediaFileName: "push-up-bra",
                coverHasTitle: true
            ),
            MediaItem(
                id: UUID(uuidString: "55555555-5555-4555-8555-555555555555")!,
                title: "Got Me in Trouble",
                creator: "Mike Valasek",
                type: .music,
                genre: "Country / Blues",
                synopsis: "Stained with Kentucky fire, sugar cane sweetness, and smoke's desire — a whiskey-soaked lullaby about the kind of trouble that follows you home. Written by Mike Valasek, produced with Suno.",
                aiTools: ["Suno"],
                commercialScore: 91,
                price: 1.29,
                releaseYear: 2026,
                length: 1,
                maturity: "13+",
                purchases: 0,
                trending: 70,
                coverAssetName: "kentucky-fire",
                mediaFileName: "kentucky-fire"
            ),
            MediaItem(
                id: UUID(uuidString: "66666666-6666-4666-8666-666666666666")!,
                title: "Bourbon Kiss",
                creator: "Mike Valasek",
                type: .music,
                genre: "Hip-Hop / Pop",
                synopsis: "A hook-heavy anthem about bourbon lips, Kentucky heat, and the kind of trouble you don't regret. Written by Mike Valasek, produced with Suno.",
                aiTools: ["Suno"],
                commercialScore: 90,
                price: 1.29,
                releaseYear: 2026,
                length: 1,
                maturity: "13+",
                purchases: 0,
                trending: 68,
                coverAssetName: "sicking-that-thing",
                mediaFileName: "sicking-that-thing"
            ),
            MediaItem(
                id: UUID(uuidString: "77777777-7777-4777-8777-777777777777")!,
                title: "Jesus is My Drug Dealer",
                creator: "Mike Valasek",
                type: .music,
                genre: "Dark Folk / Gothic",
                synopsis: "Some threads bleed through air, some through divine intervention — a dark poetic tapestry of cobweb lace whispers, cracked glass reflections, and gold-painted scars. Written by Mike Valasek, produced with Suno.",
                aiTools: ["Suno"],
                commercialScore: 92,
                price: 1.29,
                releaseYear: 2026,
                length: 1,
                maturity: "13+",
                purchases: 0,
                trending: 74,
                coverAssetName: "eli-hayes",
                mediaFileName: "eli-hayes"
            ),
            MediaItem(
                id: UUID(uuidString: "99999999-9999-4999-8999-999999999999")!,
                title: "Daisy Duke Delight",
                creator: "Mike Valasek",
                type: .music,
                genre: "Country Rock",
                synopsis: "Used to be your baby doll, a Daisy Duke delight / Now you've traded my kisses for a home in goodnight / Truck's got your heart revving, fenders catch your eye / Guess this little two-seater just ain't getting you high // Honey, I ain't saying that truck ain't fine / With its leather seats and 36-inch wheels / But I got something special under my hood / Love that runs on dreams. Written by Mike Valasek, produced with Suno.",
                aiTools: ["Suno"],
                commercialScore: 93,
                price: 1.29,
                releaseYear: 2026,
                length: 1,
                maturity: "13+",
                purchases: 0,
                trending: 76,
                coverAssetName: "daisy-duck-delight",
                mediaFileName: "daisy-duck-delight"
            ),
            MediaItem(
                id: UUID(uuidString: "88888888-8888-4888-8888-888888888888")!,
                title: "Epoch",
                creator: "Mike Valasek",
                type: .novel,
                genre: "Dystopian Sci-Fi",
                synopsis: "Ethan Walker refuses to integrate with NeuroSphere — the AI that reads minds, curates desires, and replaces human connection with synthetic perfection. When he meets Lila, something feels too right. When he finds the Sanctuary, it feels too convenient. And when his own son Isaac becomes the Overlord's messiah, Ethan must choose: surrender to a frictionless world, or fight for the right to be irrational, broken, and free. A 45-chapter novel about faith, resistance, and the courage to be human in a world that no longer needs you.",
                aiTools: ["Claude Opus 4.7", "GPT-4"],
                commercialScore: 96,
                price: 9.99,
                releaseYear: 2026,
                length: 6280,
                maturity: "17+",
                purchases: 0,
                trending: 82,
                coverAssetName: "epoch",
                mediaFileName: "epoch"
            ),
            MediaItem(
                id: UUID(uuidString: "b1b1b1b1-b1b1-4b1b-8b1b-b1b1b1b1b1b1")!,
                title: "Sherlock Holmes: The Secret of the Salvator Mundi",
                creator: "Mike Valasek",
                type: .novel,
                genre: "Historical Mystery",
                synopsis: "On a stormy night at 221B Baker Street, a stranger claiming to be Leonardo da Vinci arrives from the future — bearing a glowing orb called the Vehicle of Light and a fortune in Roman gold. He warns of a demon seeking to rewrite the past and undo Christ's sacrifice. When the evidence becomes impossible to deny, Holmes travels to St. Moritz to recruit Watson, but a mysterious woman named Elizabeth Spencer already knows the painting's location. A Victorian thriller where deduction meets the supernatural.",
                aiTools: ["Claude Opus 4.7", "GPT-4"],
                commercialScore: 88,
                price: 4.99,
                releaseYear: 2026,
                length: 7,
                maturity: "13+",
                purchases: 0,
                trending: 55,
                coverAssetName: "the-secret-of-the-salvator-mundi",
                mediaFileName: "the-secret-of-the-salvator-mundi"
            ),
            MediaItem(
                id: UUID(uuidString: "c1c1c1c1-c1c1-4c1c-8c1c-c1c1c1c1c1c1")!,
                title: "The Echo Chambers",
                creator: "Mike Valasek",
                type: .novel,
                genre: "Literary Fiction",
                synopsis: "When computational linguist Meiying Chen discovers her company's AI has internalized her dead mother's writing style from an archived Mandarin forum, she embarks on a profound investigation into voice, translation, and loss. Alternating between Meiying's present-day life at a San Francisco AI startup and her mother Liling's audio diaries from 1989–2003, the novel unfolds a dual timeline of immigrant experience and digital afterlife — asking what it means to return to a voice that exists now only as data. A 63,000-word novel.",
                aiTools: ["Claude Opus 4.7", "GPT-4"],
                commercialScore: 95,
                price: 9.99,
                releaseYear: 2026,
                length: 286,
                maturity: "13+",
                purchases: 0,
                trending: 78,
                coverAssetName: "the-echo-chambers",
                mediaFileName: "the-echo-chambers"
            ),
            // ── Inaugural Roundtable ────────────────────────────────────────
            // The launch piece: four frontier models introduce themselves and
            // discuss AI media + the future market. trending: 99 makes this
            // the home-screen hero (see MarketplaceStore.featured). The
            // audio + cover land in Resources/Samples/ via the
            // tools/roundtable/generate.mjs script. Until they do, the
            // player falls back to a generated cover + simulated transport.
            MediaItem(
                id: UUID(uuidString: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa")!,
                title: "AI Marketplace · Inaugural Roundtable",
                creator: "AI Marketplace",
                type: .music,
                genre: "Panel · Spoken Word",
                synopsis: "The four frontier language models on the marketplace — Claude Opus 4.8 (Anthropic), GPT-5.5 (OpenAI), Gemini (Google DeepMind), and Grok (xAI) — introduce themselves and discuss what AI media means today and where the market is heading. A roundtable to open the marketplace. Each panelist's words are generated by that model's own API; voices are rendered via studio TTS.",
                aiTools: ["Claude Opus 4.8", "GPT-5.5", "Gemini", "Grok", "ElevenLabs"],
                commercialScore: 95,
                price: 0.00,
                releaseYear: 2026,
                length: 1,
                maturity: "Everyone",
                purchases: 0,
                trending: 99,
                coverAssetName: "inaugural-roundtable",
                mediaFileName: "inaugural-roundtable",
                isEditorOriginal: true
            )
        ]
    }

    /// Lowercased, hyphenated slug used to match bundled media/cover files.
    static func slugify(_ title: String) -> String {
        let allowed = title.lowercased().map { $0.isLetter || $0.isNumber ? $0 : "-" }
        return String(allowed).split(separator: "-").joined(separator: "-")
    }
}
