import { ImageSourcePropType } from "react-native";

export const thumbnails: Record<string, ImageSourcePropType> = {
  v1: require("../../assets/thumbnails/v1.png"),
  v2: require("../../assets/thumbnails/v2.png"),
  v3: require("../../assets/thumbnails/v3.png"),
  v4: require("../../assets/thumbnails/v4.png"),
  v5: require("../../assets/thumbnails/v5.png"),
  v6: require("../../assets/thumbnails/v6.png"),
  v7: require("../../assets/thumbnails/v7.png"),
  v8: require("../../assets/thumbnails/v8.png"),
  v9: require("../../assets/thumbnails/v9.png"),
  v10: require("../../assets/thumbnails/v10.png"),
  v11: require("../../assets/thumbnails/v11.png"),
  v12: require("../../assets/thumbnails/v12.png"),
  v13: require("../../assets/thumbnails/v13.png"),
  v14: require("../../assets/thumbnails/v14.png"),
  v15: require("../../assets/thumbnails/v15.png"),
  v16: require("../../assets/thumbnails/v16.png"),
  v17: require("../../assets/thumbnails/v17.png"),
  v18: require("../../assets/thumbnails/v18.png"),
  v19: require("../../assets/thumbnails/v19.png"),
  v20: require("../../assets/thumbnails/v20.png"),
  v21: require("../../assets/thumbnails/v21.png"),
  v22: require("../../assets/thumbnails/v22.png"),
  v23: require("../../assets/thumbnails/v23.png"),
  v24: require("../../assets/thumbnails/v24.png"),
  v25: require("../../assets/thumbnails/v25.png"),
  v26: require("../../assets/thumbnails/v26.png"),
  v27: require("../../assets/thumbnails/v27.png"),
  v28: require("../../assets/thumbnails/v28.png"),
  v29: require("../../assets/thumbnails/v29.png"),
  v30: require("../../assets/thumbnails/v30.png"),
};

export const avatars: Record<string, ImageSourcePropType> = {
  maxout: require("../../assets/avatars/maxout.png"),
  kidventure: require("../../assets/avatars/kidventure.png"),
  gameover: require("../../assets/avatars/gameover.png"),
  sketchkings: require("../../assets/avatars/sketchkings.png"),
  buildlab: require("../../assets/avatars/buildlab.png"),
  zerogravity: require("../../assets/avatars/zerogravity.png"),
  "quiet-genius": require("../../assets/avatars/quiet-genius.png"),
  nolimits: require("../../assets/avatars/nolimits.png"),
  technaked: require("../../assets/avatars/technaked.png"),
  waveform: require("../../assets/avatars/waveform.png"),
  mindvault: require("../../assets/avatars/mindvault.png"),
  rawlaugh: require("../../assets/avatars/rawlaugh.png"),
  ironwill: require("../../assets/avatars/ironwill.png"),
  hottake: require("../../assets/avatars/hottake.png"),
  rawkitchen: require("../../assets/avatars/rawkitchen.png"),
  streetmic: require("../../assets/avatars/streetmic.png"),
  offmap: require("../../assets/avatars/offmap.png"),
  "canvas-riot": require("../../assets/avatars/canvas-riot.png"),
};
