import Foundation
import Combine

// MARK: - HermesSuggestion

/// A friendly, context-aware suggestion from Hermes.
struct HermesSuggestion: Identifiable {
    let id: UUID
    let title: String        // short headline shown in UI
    let body: String         // empathetic, plain-English explanation
    let category: SuggestionCategory
    let confidence: Double   // 0.0–1.0
    let createdAt: Date

    enum SuggestionCategory: String {
        case reminder       // "You were working on X — want to continue?"
        case caution        // "That tool failed 3 times. Here's a simpler way."
        case insight        // "You ask about Y a lot. Here's a quick explainer."
        case encouragement  // "Great progress today!"
    }
}

// MARK: - HermesProactiveEngine

/// Always-on background engine that watches memory and surfaces friendly suggestions.
/// No polling loops needed — it re-evaluates when the app foregrounds or after new observations.
actor HermesProactiveEngine {
    static let shared = HermesProactiveEngine()

    private let memory = HermesMemory.shared
    private var cachedSuggestions: [HermesSuggestion] = []
    private var lastEvaluated: Date = .distantPast

    /// Minimum gap between full re-evaluations (avoids thrashing on rapid input).
    private let minEvalInterval: TimeInterval = 60

    private init() {}

    // MARK: - Public API

    /// Returns current suggestions, re-evaluating if the cache is stale.
    func currentSuggestions() async -> [HermesSuggestion] {
        if Date().timeIntervalSince(lastEvaluated) > minEvalInterval {
            await evaluate()
        }
        return cachedSuggestions
    }

    /// Force a fresh evaluation (call on app foreground).
    func refresh() async {
        await evaluate()
    }

    // MARK: - Evaluation

    private func evaluate() async {
        lastEvaluated = Date()
        var suggestions: [HermesSuggestion] = []

        await checkUnfinishedWork(&suggestions)
        await checkRepeatedFailures(&suggestions)
        await checkDreamInsights(&suggestions)
        await checkEncouragement(&suggestions)

        // Sort: higher confidence first, max 5 shown at once
        cachedSuggestions = suggestions
            .sorted { $0.confidence > $1.confidence }
            .prefix(5)
            .map { $0 }
    }

    // MARK: - Checks

    /// If the user's last session ended mid-conversation, remind them.
    private func checkUnfinishedWork(_ out: inout [HermesSuggestion]) async {
        let messages = await memory.entries(for: "user_message")
        let responses = await memory.entries(for: "assistant_response")
        guard let lastMsg = messages.last else { return }

        // If there's a message with no response shortly after it, it was likely interrupted
        let responseAfterLast = responses.contains {
            $0.timestamp > lastMsg.timestamp && $0.timestamp.timeIntervalSince(lastMsg.timestamp) < 120
        }

        if !responseAfterLast {
            let topic = (lastMsg.content.value as? [String: Any])?["text"] as? String ?? "your last question"
            let preview = String(topic.prefix(60))
            out.append(HermesSuggestion(
                id: UUID(),
                title: "Pick up where you left off?",
                body: "Looks like we got interrupted. You were asking: \"\(preview)…\" — want to continue that?",
                category: .reminder,
                confidence: 0.85,
                createdAt: Date()
            ))
        }
    }

    /// Surface a friendly caution if the same tool keeps failing.
    private func checkRepeatedFailures(_ out: inout [HermesSuggestion]) async {
        let execs = await memory.entries(for: "tool_exec")
        let recent = execs.filter { $0.timestamp > Date().addingTimeInterval(-3600) }

        let failures = recent.compactMap { entry -> String? in
            guard let d = entry.content.value as? [String: Any],
                  let ok = d["success"] as? Bool, !ok,
                  let name = d["tool"] as? String else { return nil }
            return name
        }

        let counts = Dictionary(failures.map { ($0, 1) }, uniquingKeysWith: +)
        for (tool, count) in counts where count >= 3 {
            out.append(HermesSuggestion(
                id: UUID(),
                title: "'\(tool)' keeps failing",
                body: "That tool has run into trouble \(count) times in the last hour. It might need different input, or there could be a config issue — want me to take a look?",
                category: .caution,
                confidence: min(0.5 + Double(count) * 0.1, 0.95),
                createdAt: Date()
            ))
        }
    }

    /// Bubble up insights generated by DreamEngine.
    private func checkDreamInsights(_ out: inout [HermesSuggestion]) async {
        let insights = await memory.entries(for: "dream_insight")
            .filter { $0.timestamp > Date().addingTimeInterval(-86400) } // last 24 h
        for insight in insights.prefix(2) {
            let text = (insight.content.value as? [String: Any])?["insight"] as? String ?? ""
            guard !text.isEmpty else { continue }
            out.append(HermesSuggestion(
                id: UUID(),
                title: "Something I noticed while you were away",
                body: text + " — let me know if you'd like to explore any of these topics.",
                category: .insight,
                confidence: 0.7,
                createdAt: insight.timestamp
            ))
        }

        // Self-improvement notes from DreamEngine
        let improvements = await memory.entries(for: "self_improvement")
            .filter { $0.timestamp > Date().addingTimeInterval(-86400) }
        for imp in improvements.prefix(1) {
            let note = (imp.content.value as? [String: Any])?["note"] as? String ?? ""
            guard !note.isEmpty else { continue }
            out.append(HermesSuggestion(
                id: UUID(),
                title: "Quick heads-up",
                body: note,
                category: .caution,
                confidence: 0.8,
                createdAt: imp.timestamp
            ))
        }
    }

    /// Occasionally send a warm, encouraging message when activity is high.
    private func checkEncouragement(_ out: inout [HermesSuggestion]) async {
        let todayStart = Calendar.current.startOfDay(for: Date())
        let todayMessages = await memory.entries(for: "user_message")
            .filter { $0.timestamp >= todayStart }

        // Only encourage after a productive session (10+ messages today)
        guard todayMessages.count >= 10 else { return }

        // Don't repeat encouragement more than once a day
        let alreadyEncouraged = await memory.entries(for: "encouragement_sent")
            .contains { $0.timestamp >= todayStart }
        guard !alreadyEncouraged else { return }

        out.append(HermesSuggestion(
            id: UUID(),
            title: "You're on a roll today",
            body: "You've been working through a lot — \(todayMessages.count) messages today alone. Don't forget to take a break when you need one. I'll be here when you get back.",
            category: .encouragement,
            confidence: 0.6,
            createdAt: Date()
        ))

        // Mark that we sent encouragement so we don't repeat it
        try? await memory.observe(
            category: "encouragement_sent",
            content: ["count": todayMessages.count],
            metadata: ["importance": 1]
        )
    }
}

// MARK: - SwiftUI integration helper

/// Thin ObservableObject wrapper so SwiftUI views can observe suggestions reactively.
@MainActor
final class HermesViewModel: ObservableObject {
    @Published var suggestions: [HermesSuggestion] = []
    @Published var isLoading = false

    func refresh() {
        isLoading = true
        Task {
            let fresh = await HermesProactiveEngine.shared.currentSuggestions()
            self.suggestions = fresh
            self.isLoading = false
        }
    }
}
