#!/bin/sh
# Xcode Cloud — post-clone hook.
#
# Runs once after Xcode Cloud clones the repo, before the build starts.
# Path convention: ci_scripts/ci_post_clone.sh next to the .xcodeproj.
#
# Materializes Secrets.xcconfig from Xcode Cloud environment variables
# so that AIMKT_WORKER_URL and AIMKT_SHARED_SECRET are baked into the
# binary at build time. Creators then never need to configure anything.

set -eu

echo "── Xcode Cloud post-clone ──"
echo "Branch: ${CI_BRANCH:-?}"
echo "Commit: ${CI_COMMIT:-?}"
echo "Workflow: ${CI_WORKFLOW:-?}"
echo "Xcode: $(xcodebuild -version | head -1)"
echo "Swift: $(swift --version | head -1)"
echo "Working dir: $(pwd)"

# ── Write Secrets.xcconfig from Xcode Cloud env vars ──
# Set AIMKT_WORKER_URL and AIMKT_SHARED_SECRET in
# Xcode Cloud → Workflow → Environment Variables.
#
# CRITICAL: Build.xcconfig (at ./Config/) uses #include? "Secrets.xcconfig"
# which resolves relative to ./Config/. So Secrets.xcconfig MUST exist at
# ./Config/Secrets.xcconfig — NOT just at ./AIMarketplace/Config/.
# We write to BOTH locations so Xcode finds it via #include? AND the
# pbxproj file reference (AIMarketplace/Config/) is also satisfied.

SECRETS_DIR_1="Config"
SECRETS_DIR_2="AIMarketplace/Config"

write_secrets() {
  local dir="$1"
  local fpath="${dir}/Secrets.xcconfig"
  echo "// Secrets.xcconfig — generated by ci_post_clone.sh" > "$fpath"
  echo "" >> "$fpath"
  echo "AIMKT_WORKER_URL = ${AIMKT_WORKER_URL}" >> "$fpath"
  echo "AIMKT_SHARED_SECRET = ${AIMKT_SHARED_SECRET}" >> "$fpath"
  echo "Secrets.xcconfig: WRITTEN to ${fpath} from env vars ✓"
}

if [ -n "${AIMKT_WORKER_URL:-}" ] && [ -n "${AIMKT_SHARED_SECRET:-}" ]; then
  write_secrets "$SECRETS_DIR_1"
  write_secrets "$SECRETS_DIR_2"
else
  # Fallback: check if file already exists in repo (e.g. dev builds)
  if [ -f "${SECRETS_DIR_1}/Secrets.xcconfig" ]; then
    echo "Secrets.xcconfig: present in ${SECRETS_DIR_1}/ (no env vars needed)"
  elif [ -f "${SECRETS_DIR_2}/Secrets.xcconfig" ]; then
    echo "Secrets.xcconfig: present in ${SECRETS_DIR_2}/ (no env vars needed)"
    # Copy to ./Config/ so Build.xcconfig's #include? finds it
    cp "${SECRETS_DIR_2}/Secrets.xcconfig" "${SECRETS_DIR_1}/Secrets.xcconfig"
    echo "Secrets.xcconfig: COPIED from ${SECRETS_DIR_2}/ to ${SECRETS_DIR_1}/ for #include? ✓"
  else
    echo "Secrets.xcconfig: absent (defaults to empty; admin configures at runtime)"
    echo "⚠️  Set AIMKT_WORKER_URL + AIMKT_SHARED_SECRET in Xcode Cloud env vars to auto-bake"
  fi
fi

echo "── post-clone done ──"