#!/bin/sh
# Xcode Cloud — post-clone hook.
#
# Runs once after Xcode Cloud clones the repo, before the build starts.
# Path convention: ci_scripts/ci_post_clone.sh next to the .xcodeproj.
#
# Materializes Secrets.xcconfig from Xcode Cloud environment variables
# so that AIMKT_WORKER_URL and AIMKT_SHARED_SECRET are baked into the
# binary at build time. Creators then never need to configure anything.

set -eu

echo "── Xcode Cloud post-clone ──"
echo "Branch: ${CI_BRANCH:-?}"
echo "Commit: ${CI_COMMIT:-?}"
echo "Workflow: ${CI_WORKFLOW:-?}"
echo "Xcode: $(xcodebuild -version | head -1)"
echo "Swift: $(swift --version | head -1)"
echo "Working dir: $(pwd)"

# ── Write Secrets.xcconfig from Xcode Cloud env vars ──
# Set AIMKT_WORKER_URL and AIMKT_SHARED_SECRET in
# Xcode Cloud → Workflow → Environment Variables.
SECRETS_FILE="AIMarketplace/Config/Secrets.xcconfig"

if [ -n "${AIMKT_WORKER_URL:-}" ] && [ -n "${AIMKT_SHARED_SECRET:-}" ]; then
  echo "// Secrets.xcconfig — generated by ci_post_clone.sh" > "$SECRETS_FILE"
  echo "" >> "$SECRETS_FILE"
  echo "AIMKT_WORKER_URL = ${AIMKT_WORKER_URL}" >> "$SECRETS_FILE"
  echo "AIMKT_SHARED_SECRET = ${AIMKT_SHARED_SECRET}" >> "$SECRETS_FILE"
  echo "Secrets.xcconfig: WRITTEN from env vars ✓"
else
  # Fallback: check if file already exists in repo (e.g. dev builds)
  if [ -f "$SECRETS_FILE" ]; then
    echo "Secrets.xcconfig: present in repo (no env vars needed)"
  else
    echo "Secrets.xcconfig: absent (defaults to empty; admin configures at runtime)"
    echo "⚠️  Set AIMKT_WORKER_URL + AIMKT_SHARED_SECRET in Xcode Cloud env vars to auto-bake"
  fi
fi

echo "── post-clone done ──"
